### ISSUE TITLE
Minor Readme Issue

### ISSUE THREAD

**Issue by dougblackjr** [PrimitiveSocial/clockwork#1]
Hey all! This package is awesome!

When implementing this, I followed the step in the Usage section of the readme:
`import {_v} from "primitivesocial/clockwork";`

However, had to implement this as
`import {_v} from "@primitivesocial/clockwork";` (added the `@` in there).

Not sure if this is just a me thing, or needs to be corrected. Let me know how I can help!

**Comment by elie-primitivesocial** [comment]
@dougblackjr Woops! yeah just a typo in the doc. I will update it.
